CMS_Elite/Areas/Admin/Controllers/RoleUserController.cs
using CMS_Elite.Controllers;
using CMS_Elite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CMS_Elite.Areas.Admin.Controllers
{
    public class RoleUserController : BaseController
    {
        #region Variables
        CMSEliteDbContext db;
        #endregion
        // GET: Admin/RoleUser
        public ActionResult Index()
        {
            SetTable();
            return View();
        }

        public JsonResult SaveData(string ID, String Choice)
        {
            //Thực hiện cập nhật dữ liệu
            var strID = ID.Replace("chk_", "").Replace(" ", "").Trim();
            var arrID = strID.Split('_');
            var UserID = arrID[0].ToString();
            var RoleID = arrID[1].ToString();
            db = new CMSEliteDbContext();
            if (Choice.ToUpper() == "TRUE")
            {
                //Thực hiện ghi dữ liệu
                var item = new tblUser_Role();
                item.ID = -1;
                item.UserID = Convert.ToInt32(RoleID);
                item.RoleID = UserID;

                db.tblUser_Role.Add(item);
                var result = db.SaveChanges();
                if (result > 0)
                {
                    return Json("OK", JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                //Xóa dữ liệu
                var uID = Convert.ToInt32(RoleID);
                var item = db.tblUser_Role.Where(x => x.RoleID == UserID && x.UserID == uID).SingleOrDefault();
                var Result = db.tblUser_Role.Remove(item);
                db.SaveChanges();
                if (Result != null)
                {
                    return Json("KO", JsonRequestBehavior.AllowGet);
                }
            }
            return Json("OK", JsonRequestBehavior.AllowGet);

        }
        [HttpPost]
        //public ActionResult Index(FormCollection collection)
        //{
        //    SetTable();

        //    //Xóa dữ liệu
        //    for (int i = 1; i < collection.AllKeys.Count(); i++)
        //    {
        //        if (collection.AllKeys[i].Contains('_') == true)
        //        {
        //            var arr = collection.AllKeys[i].ToString().Split('_');
        //            string MA_NVIEN = arr[2].ToString().Trim();
        //        }
        //    }
        //    //Ghi dữ liệu
        //    string resInsert = "";
        //    for (int i = 1; i < collection.AllKeys.Count(); i++)
        //    {
        //        if (collection.AllKeys[i].Contains("_") == true)
        //        {
        //            var arr = collection.AllKeys.ToString().Split('_');
        //            string MA_QUYEN = arr[1].ToString().Trim();
        //            string MA_NVIEN = arr[2].ToString().Trim();
        //        }
        //    }

        //    if (resInsert == "OK")
        //    {
        //        //SetAlert("Success", "Thêm mới dữ liệu thành công");
        //        return RedirectToAction("Index", "RoleUser");
        //    }
        //    else
        //    {
        //        //SetAlert("Error", "Lỗi trong quá trình thêm dữ liệu:" + resInsert);
        //        return View();
        //    }
        //}

        #region Public funtions
        private void SetTable()
        {
            try
            {
                db = new CMSEliteDbContext();
                var lstRole = db.tblRoles.ToList();
                Session["Role"] = lstRole;

                var lstUser = db.tblUsers.ToList();
                Session["User"] = lstUser;

                var lstQuyen = (from a in db.tblUsers
                                join b in db.tblUser_Role
                                on a.ID equals b.UserID
                                where a.Status == 1
                                select new
                                {
                                    ID = a.ID,
                                    UserName = a.UserName,
                                    RoleID = b.RoleID,
                                }).ToList();
                List<tblUser_Role> iUserRole = new List<tblUser_Role>();
                foreach (var item in lstQuyen)
                {
                    tblUser_Role iNew = new tblUser_Role();
                    iNew.ID = item.ID;
                    iNew.RoleID = item.RoleID;
                    iNew.UserID = item.ID;
                    iUserRole.Add(iNew);
                }
                Session["User_Role"] = iUserRole;
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                throw;
            }
        }
        #endregion
    }
}

CMS_Elite/Areas/Admin/Views/RoleUser/Index.cshtml
@model IEnumerable<CMS_Elite.Models.tblUser_Role>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@{
    var modelQuyen = (IEnumerable<CMS_Elite.Models.tblRole>)Session["Role"];
    var modelNVien = (IEnumerable<CMS_Elite.Models.tblUser>)Session["User"];
    var modelQLQuyen = new List<CMS_Elite.Models.tblUser_Role>();
    if (Session["User_Role"] != null)
    {
        modelQLQuyen = (List<CMS_Elite.Models.tblUser_Role>)Session["User_Role"];
    }
}
@using (Html.BeginForm("Index", "RoleUser", FormMethod.Post))
{
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body table-border-style">
                    <div class="row">
                        <div class="col-lg-6">
                            <h4 class="card-title">Quyền người dùng</h4>
                        </div>
                        <div class="col-lg-6">
                            <a href="@Url.Action("Create", "UserRole")" class="btn btn-sm btn-primary btn-header">Thêm mới</a>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table id="myTable" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th style="text-align:center; width:auto">TÊN TÀI KHOẢN</th>
                                    @foreach (var item in modelQuyen)
                                    {
                                        <th style="text-align:center; width:200px">@item.RoleName</th>
                                    }


                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in modelNVien)
                                {

                                    <tr>
                                        <td style="text-align:center">
                                            @item.UserName
                                        </td>


                                        @foreach (var itemDetail in modelQuyen)
                                        {
                                            var icheck = false;
                                            <td>
                                                @foreach (var itemcheck in modelQLQuyen)
                                                {
                                                    if (itemcheck.RoleID == itemDetail.RoleID && itemcheck.UserID == item.ID)
                                                    {
                                                        icheck = true;
                                                        break;
                                                    }

                                                }
                                                @if (icheck == true)
                                                {
                                                    <input type="checkbox" onchange="show(this.id)" id="chk_@itemDetail.RoleID _@item.ID" name="chk_@itemDetail.RoleID _@item.ID" value="true" checked="true" />
                                                }
                                                else
                                                {
                                                    <input type="checkbox" onchange="show(this.id)" id="chk_@itemDetail.RoleID _@item.ID" name="chk_@itemDetail.RoleID _@item.ID" value="fale" />
                                                }
                                            </td>
                                        }
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>

}

<div class="modal fade" id="myModal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content" id="modelContent">
        </div>
    </div>
</div>
<script>
    function createModal(url) {
        $('#modelContent').load(url);
        $('#myModal').modal('show');
    }
</script>

<script>
    $(document).ready(function () {
        $('#myTable').DataTable();
        $(document).ready(function () {
            var table = $('#example').DataTable({
                "columnDefs": [{
                    "visible": false,
                    "targets": 2
                }],
                "order": [
                    [2, 'asc']
                ],
                "displayLength": 25,
                "drawCallback": function (settings) {
                    var api = this.api();
                    var rows = api.rows({
                        page: 'current'
                    }).nodes();
                    var last = null;
                    api.column(2, {
                        page: 'current'
                    }).data().each(function (group, i) {
                        if (last !== group) {
                            $(rows).eq(i).before('<tr class="group"><td colspan="5">' + group + '</td></tr>');
                            last = group;
                        }
                    });
                }
            });
            // Order by the grouping
            $('#example tbody').on('click', 'tr.group', function () {
                var currentOrder = table.order()[0];
                if (currentOrder[0] === 2 && currentOrder[1] === 'asc') {
                    table.order([2, 'desc']).draw();
                } else {
                    table.order([2, 'asc']).draw();
                }
            });
        });
    });
    $('#example23').DataTable({
        dom: 'Bfrtip',
        buttons: [
            'copy', 'csv', 'excel', 'pdf', 'print'
        ]
    });
</script>
<script>
    function show(id) {
        var chk = document.getElementById(id).checked;
        var jsData = "{ID:'" + id + "', Choice:'" + chk + "'}";
        $.ajax({
            type: "POST",
            url: "/RoleUser/SaveData",
            contentType: "application/json; charset=utf-8",
            data: jsData,
            dataType: "json",
            success: function (chData) {
                if (chData == "OK") {
                    SetAlert("Success", "Ghi dữ liệu thành công", "");
                }
                else if (chData == "KO") {
                    SetAlert("waring", "Loại dữ liệu thành công", "");
                }
            }
        })
    }
</script>

@*setalert chạy trong view*@
<script type="text/javascript">
    function SetAlert(type, warningtext, idfocus) {
        if (type == "sucess") {
            window.setTimeout(function () {
                $.toast({
                    heading: 'Thông báo',
                    text: warningtext,
                    position: "top-right",
                    loaderBg: '#e69a2a',
                    icon: 'sucess',
                    hiedeAfter: 3500,
                    stack: 6
                });
            }, 1000);
        }

        else if (type == "waring") {
            window.setTimeout(function () {
                $.toast({
                    heading: 'Thông báo',
                    text: warningtext,
                    position: "top-right",
                    loaderBg: '#f35800',
                    icon: 'waring',
                    hiedeAfter: 3500,
                    stack: 6
                });
            }, 1000);
        }
        else {
            window.setTimeout(function () {
                $.toast({
                    heading: 'Thông báo',
                    text: warningtext,
                    position: "top-right",
                    loaderBg: '#f35800',
                    icon: 'danger',
                    hiedeAfter: 3500,
                    stack: 6
                });
            }, 1000);
        }
    }
</script>